### ISSUE TITLE
2010 x64 downloadlink

### ISSUE THREAD

**Issue by blackcrack** [WPN-XM/vcredist#1]
https://www.microsoft.com/en-us/download/details.aspx?id=14632
https://www.microsoft.com/en-us/download/confirmation.aspx?id=14632

DDL:
https://download.microsoft.com/download/3/2/2/3224B87F-CFA0-4E70-BDA3-3DE650EFEBA5/vcredist_x64.exe

**Comment by jakoch** [comment]
Thank you for contributing. 👍
